### PR TITLE
Fixed CS_ERR_MEM returned from cs_open in CodeDisasm::Init

### PR DESCRIPTION
**Pull request by Zachareee**
Initialised dynamic memory allocation in capstone dependency through cs_option with default memory management functions in cstdlib

### CODE REVIEW

**Comment by Nemirtingas** [comment]
Hi, can you explain the issue with Capstone ? I use this library quite often and never encountered any issue on CodeDisasm::Init.

**Comment by Zachareee** [comment]
Hi Nemirtingas, I was tracing function calls and I found that cs_option has to be called before cs_open, I was using Base_Hook::HookFunc in your ingame_overlay repo which requires Init to return CS_ERR_OK or it won't work
```
CAPSTONE_EXPORT
cs_err CAPSTONE_API cs_open(cs_arch arch, cs_mode mode, csh *handle)
{
	cs_err err;
	struct cs_struct *ud;
	if (!cs_mem_malloc || !cs_mem_calloc || !cs_mem_realloc || !cs_mem_free || !cs_vsnprintf)
		// Error: before cs_open(), dynamic memory management must be initialized
		// with cs_option(CS_OPT_MEM)
		return CS_ERR_MEMSETUP;
```
https://github.com/Nemirtingas/mini_detour/blob/5567f037cb3df785e9bd29baf166ced848262c67/deps/capstone/cs.c#L479C4-L479C4

Also I'm somewhat new to contributing to open source and stuff so I hope you can forgive if I make any mistakes or being unclear anywhere

**Comment by Nemirtingas** [comment]
I meant, what issue did you encounter that made you modify the code to call `cs_option(NULL, cs_opt_type::CS_OPT_MEM, (size_t) &mem);` in the first place, as I don't need to use this option to have mini_detour working on Windows, Linux and MacOS.

**Comment by Nemirtingas** [comment]
No response from creator. Feel free to re-open if you have any further information.

**Comment by Zachareee** [comment]
Hi, I inspected the capstone dependency in slightly more detail and I realised that I was missing a flag in my compilation step to use the default memory allocation in the system. I am very sorry about the confusion and inconveniences caused

**Pull request closed without merging**
